# server options
auto: true
pygments: true
#server_port: 4000
markdown: rdiscount
rdiscount:
 extensions: [smart]

# blog metadata
author: Hui Zheng
title: Thinking in Thinking
subtitle: Hui Zheng's blog
permalink: /:year/:month/:day/:title

# web services
gravatar: 65771458eb066098b716e6ee31df1738
disqus: hzheng
twitter: xyz98
ga: UA-29218291-1

# URLs
url: http://en.zhenghui.org
feed: http://en.zhenghui.org/feed
atom: http://en.zhenghui.org/feed/atom.xml
feedburner: http://feeds.feedburner.com/xyz98
github_home: https://github.com/hzheng

# directories
js_dir: /assets/js
css_dir: /assets/css
img_dir: /assets/image
xml_dir: /assets/xml
